import type { VectorScene } from "./pdfVectorExtractor";

/** Shared empty scene for vector extraction and raster page fallback. */
export function createEmptyVectorScene(): VectorScene {
  return {
    pageCount: 0,
    pagesPerRow: 1,
    pageRects: new Float32Array(0),
    pageTextRanges: new Uint32Array(0),
    textIndex: null,
    fillPathCount: 0,
    fillSegmentCount: 0,
    fillPathMetaA: new Float32Array(0),
    fillPathMetaB: new Float32Array(0),
    fillPathMetaC: new Float32Array(0),
    fillSegmentsA: new Float32Array(0),
    fillSegmentsB: new Float32Array(0),
    gradientCount: 0,
    gradientMetaA: new Float32Array(0),
    gradientMetaB: new Float32Array(0),
    gradientMetaC: new Float32Array(0),
    gradientMetaD: new Float32Array(0),
    gradientMetaE: new Float32Array(0),
    gradientLut: new Uint8Array(0),
    gradientFillPathCount: 0,
    gradientFillSegmentCount: 0,
    gradientFillPathMetaA: new Float32Array(0),
    gradientFillPathMetaB: new Float32Array(0),
    gradientFillPathMetaC: new Float32Array(0),
    gradientFillPaintMeta: new Float32Array(0),
    gradientFillSegmentsA: new Float32Array(0),
    gradientFillSegmentsB: new Float32Array(0),
    gradientStrokeRunCount: 0,
    gradientStrokeSegmentCount: 0,
    gradientStrokeRunMetaA: new Float32Array(0),
    gradientStrokeRunMetaB: new Float32Array(0),
    gradientStrokeEndpoints: new Float32Array(0),
    gradientStrokePrimitiveMeta: new Float32Array(0),
    gradientStrokePrimitiveBounds: new Float32Array(0),
    gradientStrokeStyles: new Float32Array(0),
    segmentCount: 0,
    sourceSegmentCount: 0,
    mergedSegmentCount: 0,
    sourceTextCount: 0,
    textInstanceCount: 0,
    textGlyphCount: 0,
    textGlyphSegmentCount: 0,
    textInPageCount: 0,
    textOutOfPageCount: 0,
    textInstanceA: new Float32Array(0),
    textInstanceB: new Float32Array(0),
    textInstanceC: new Float32Array(0),
    textGlyphMetaA: new Float32Array(0),
    textGlyphMetaB: new Float32Array(0),
    textGlyphSegmentsA: new Float32Array(0),
    textGlyphSegmentsB: new Float32Array(0),
    rasterLayers: [],
    rasterLayerWidth: 0,
    rasterLayerHeight: 0,
    rasterLayerData: new Uint8Array(0),
    rasterLayerMatrix: new Float32Array([1, 0, 0, 1, 0, 0]),
    endpoints: new Float32Array(0),
    primitiveMeta: new Float32Array(0),
    primitiveBounds: new Float32Array(0),
    styles: new Float32Array(0),
    bounds: { minX: 0, minY: 0, maxX: 1, maxY: 1 },
    pageBounds: { minX: 0, minY: 0, maxX: 1, maxY: 1 },
    maxHalfWidth: 0,
    imagePaintOpCount: 0,
    operatorCount: 0,
    pathCount: 0,
    discardedTransparentCount: 0,
    discardedDegenerateCount: 0,
    discardedDuplicateCount: 0,
    discardedContainedCount: 0
  };
}

